default:
  navigation:
    - title: Productos
      subtitle: Categories
      url: /t/productos
      items:
        - :title: Panes
          :url: /t/productos/panes
        - :title: Pastelería
          :url: /t/productos/pasteleria
        - :title: Quesos
          :url: /t/productos/quesos
        - :title: Embutidos
          :url: /t/productos/embutidos
        - :title: Conservas
          :url: /t/productos/conservas
      promo_banners:
        - subtitle: Del campo a tu mesa
          title: Los mejores quesos
          url: /t/productos/quesos
          image: "meganav/aliona-gumeniuk-jeAjT87nbjM-unsplash_l41mvh.jpg"
        - subtitle: Horneados cada día
          title: Los mejores panes
          url: /t/productos/panes
          image: "meganav/wesual-click-rsWZ-P9FbQ4-unsplash_mu5zy4.jpg"
    - title: Inspiración
      subtitle: Categories
      url: /t/inspiracion
      items:
        - :title: Picnic bajo el sol
          :url: /t/inspiracion/picnic
        - :title: Verano
          :url: /t/inspiracion/verano
        - :title: Cena familiar
          :url: /t/inspiracion/cena
        - :title: Reunión de negocios
          :url: /t/inspiracion/negocios
      promo_banners:
        - subtitle: Disfruta al aire libre
          title: Picnic bajo el sol
          url: /t/inspiracion/picnic
          image: "meganav/toa-heftiba-q1QDZtYP2ow-unsplash.jpg"
        - subtitle: Horneados cada día
          title: Cena familiar
          url: /t/inspiracion/cena-familiar
          image: "meganav/gor-davtyan-b1aT3t3uq2E-unsplash.jpg"
    - title: Tablas
      subtitle: Categories
      url: /t/tablas
      items:
        - :title: Picada
          :url: /t/tablas/picada
        - :title: Gourmet
          :url: /t/tablas/gourmet
        - :title: Degustar
          :url: /t/tablas/degustar
      promo_banners:
        - subtitle: Disfruta de nuestra variedad
          title: Picada
          url: /t/tablas/picada
          image: "meganav/tim-toomey-oHNkcwHjBSY-unsplash.jpg"
        - subtitle: Nuestra tabla gourmet
          title: Gourmet
          url: /t/tablas/gourmet
          image: "meganav/zan-30809AYY3rg-unsplash.jpg"
